server:
  port: 8060
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/goodsFlow
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

# Feign
# api key
api-key : 45322f29cc1e48ef9a5157d1fa09bbbd
# goodsFlow api url
base-url: https://test-api.goodsflow.io:443

##배송추적

#운송장 등록
tracking-post: /api/deliveries/tracking
#UniqueId 변경
tracking-put: /api/deliveries/uniqueId/change
#취소
tracking-delete: /api/deliveries/cancel

