package jidoly.goodsflow.feign.dto;

public enum ReasonType {
    PICKUP_DELAY, OTHER_SERVICE, RE_RECEIVED, ABSENCE_CUSTOMER, PICKUP_OTHER, EXCEED_BOX, POOR_PACKAGE, NO_ITEM, ERROR_ITEM, SENDER_CANCEL, PICKUP_FAIL, CHANGE_MIND
}
